version: "3.5"
services:
  db:
    image: postgres:12-alpine3.15
    container_name: food_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  api:
    build:
      context: .
      dockerfile: ./back-end/Dockerfile
    container_name: food_api
    ports:
      - 3100:3100
    env_file: ./back-end/.envrc
    entrypoint: entrypoint.sh
    environment:
      RAILS_ENV: development
    volumes:
      - ./back-end/.:/foods/back-end
    command: ["rails", "s", "-p", "3100", "-b", "0.0.0.0"]
    depends_on:
      - db
  client:
    build:
      context: .
      dockerfile: ./front-end/Dockerfile
    container_name: food_ui
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
    volumes:
      - ./front-end/.:/foods/front-end
    env_file: ./front-end/.env
    depends_on:
      - api